# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('firstTrainMonSat', models.TimeField(blank=True)),
                ('lastTrainMonSat', models.TimeField(blank=True)),
                ('firstTrainSun', models.TimeField(blank=True)),
                ('lastTrainSun', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcrawl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('date_time', models.DateTimeField()),
                ('is_public', models.BooleanField()),
                ('loc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcrawl_loc', to='pubway.Place')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_reviews', models.IntegerField(default=0)),
                ('no_likes', models.IntegerField(default=0)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('subcrawls', models.ManyToManyField(to='pubway.Subcrawl')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subcrawl',
            name='organiser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pubway.UserProfile'),
        ),
        migrations.AddField(
            model_name='subcrawl',
            name='places',
            field=models.ManyToManyField(to='pubway.Place'),
        ),
    ]
