# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='mapCoords',
            field=models.CharField(default='0,0,0,0', max_length=32),
        ),
    ]
