# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='firstTrainMonSat',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='firstTrainSun',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lastTrainMonSat',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='lastTrainSun',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
