# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0002_auto_20180306_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
