# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0002_station_mapcoords'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.IntegerField(choices=[(0, 'Pub'), (1, 'Restaurant'), (2, 'Nightclub'), (3, 'Other')], default=0),
        ),
    ]
