# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0003_station_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='stringName',
            field=models.CharField(default='', max_length=128),
        ),
    ]
