# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0004_station_stringname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='stringName',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='place',
            name='closeStation',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pubway.Station'),
        ),
        migrations.AddField(
            model_name='place',
            name='isNightClub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='isOther',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='isPub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='isRestaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='place',
            name='postcode',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='place',
            name='website',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
