# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0004_auto_20180322_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='website',
            new_name='url',
        ),
    ]
