# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0006_station_stringname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='isNightClub',
        ),
        migrations.RemoveField(
            model_name='place',
            name='isOther',
        ),
        migrations.RemoveField(
            model_name='place',
            name='isPub',
        ),
        migrations.RemoveField(
            model_name='place',
            name='isRestaurant',
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.IntegerField(choices=[(1, 'Pub'), (2, 'Restaurant'), (3, 'Nightclub'), (4, 'Other')], default=1),
        ),
        migrations.AlterField(
            model_name='place',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
