# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0007_auto_20180312_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'places'},
        ),
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name_plural': 'stations'},
        ),
    ]
