# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0007_auto_20180312_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='closeStation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pubway.Station'),
        ),
    ]
