# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0008_auto_20180313_1424'),
        ('pubway', '0008_auto_20180313_1324'),
    ]

    operations = [
    ]
