# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0010_auto_20180313_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_images')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pubway.Place')),
            ],
        ),
        migrations.RemoveField(
            model_name='station',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='station',
            name='longitude',
        ),
    ]
