# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0013_auto_20180315_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcrawl',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
