# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0016_place_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='id',
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
