# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0017_auto_20180316_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='stringName',
        ),
    ]
