# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0013_auto_20180318_1648'),
        ('pubway', '0018_remove_station_stringname'),
    ]

    operations = [
    ]
