# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubway', '0019_merge_20180318_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='mapCoords',
            field=models.CharField(default='0,0,0,0', max_length=32),
        ),
    ]
